### PR TITLE
Fix/lv redeem ctds

### PR DESCRIPTION
**Pull request by ziankork**
# Changes

List of Changes: 
 - apply exchange rate when LV redeem CT + DS on the PSM

### CODE REVIEW

**Comment by siddhpurakaran** [comment]
I think if we are returning empetied amount then we may also have to check 2 files and update them if required..

IDsFlashSwapRouter.sol
Because netspec comment is saying it is returning reserve amount(instead of emptied amount) in emptyReservePartial function
VaultLib.sol
In _redeemCtDsAndSellExcessCt function we are using emptyReservePartial function's return value as reserve amount

**Comment by siddhpurakaran** [comment]
we are using lvRedeemRaWithCtDs function's return value as redeemAmount then we can remove below line (line no 376 here) and directly declare redeemAmount in next line

 uint256 redeemAmount = reservedDs >= ctAmm ? ctAmm : reservedDs;

**Comment by ziankork** [comment]
> I think if we are returning empetied amount then we may also have to check 2 files and update them if required..
> 
> IDsFlashSwapRouter.sol Because netspec comment is saying it is returning reserve amount(instead of emptied amount) in emptyReservePartial function VaultLib.sol In _redeemCtDsAndSellExcessCt function we are using emptyReservePartial function's return value as reserve amount

already updated the natspec

**Comment by siddhpurakaran** [comment]
lgtm

**Pull request merged**
